### PR TITLE
bundler 1.10 compatibility; rslt version bump to 1.1.9

### PR DESCRIPTION
**Pull request by smcphill**
To resolve https://lonelyplanet.slack.com/archives/atlas2ninjas/p1432860078000217, `rslt.gemspec` has been updated to support Bundler v > 1.9.8.

Previously, the gemspec was maintained by the `Jeweler` gem. I've ditched this, and it's `Rakefile`. I've also cleared out older (pre ruby2) gemspec paths.

### CODE REVIEW

**Comment by smcphill** [comment]
### Testing outcomes:

#### Rspec

```
(devmac-12) (15:04:54) ~/projects/remixer [master] 'Steven McPhillips' 2.1.0p0
$ ber spec:covered
...
Finished in 2 minutes 11.7 seconds
4993 examples, 0 failures
...
Coverage report generated for RSpec to /Users/dev/projects/remixer/target/reports/coverage. 9695 / 9695 LOC (100.0%) covered.
```

#### Cuke

```
(devmac-12) (15:19:50) ~/projects/remixer [master] 'Steven McPhillips' 2.1.0p0
$ COMPARE_PDFS=false bec
...
171 scenarios (171 passed)
2170 steps (2170 passed)
7m41.964s
```

**Comment by smcphill** [comment]
Remixer diff (rslt path / github change is temporary to test without updating rslt#master)

```
diff --git a/Gemfile b/Gemfile
index c035982..da74eab 100644
--- a/Gemfile
+++ b/Gemfile
@@ -15,7 +15,8 @@ gem 'json'
 gem 'aws-sdk'

 gem "rest-client"
-gem "rslt", :github => "lonelyplanet/rslt"
+#gem "rslt", :github => "lonelyplanet/rslt"
+gem "rslt", :path => "vendor/gems/rslt-1.1.9"
 gem 'uuid'
 gem 'script_detector', "~> 0.1.2"

diff --git a/Gemfile.lock b/Gemfile.lock
index 1ac5d51..93028a8 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -1,14 +1,4 @@
 GIT
-  remote: git://github.com/lonelyplanet/rslt.git
-  revision: 5ad6e5605ecb68ed1054157f7cddee09042092b9
-  specs:
-    rslt (1.1.8)
-      builder (> 2)
-      builder
-      nokogiri
-      nokogiri (~> 1)
-
-GIT
   remote: https://b6490044558e9d12b65fbdce64773ffc5c075e2d:x-oauth-basic@github.com/lonelyplanet/spp_aws.git
   revision: 3da1358839d645628d7ed1145860c3953c2f52b8
   specs:
@@ -27,6 +17,13 @@ GIT
     lp_on_rails (0.2.0)
       aws-sdk

+PATH
+  remote: vendor/gems/rslt-1.1.9
+  specs:
+    rslt (1.1.9)
+      builder (~> 3)
+      nokogiri (~> 1)
+
 GEM
   remote: http://rubygems.org/
   specs:
@@ -351,3 +348,6 @@ DEPENDENCIES
   uglifier
   uuid
   will_paginate (~> 3.0.5)
```

**Comment by lukerobins** [comment]
Assuming a ber running all the tests works for remixer I :+1: your slash and burn

**Comment by smcphill** [comment]
Thanks @lukerobins . As discussed, I've removed the pin for activesupport here, and introduced it to remixer - there'll be a partner PR appearing there shortly!

**Pull request merged**
